version: '2.2'
services:
    foodfacts-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ~/volumes/foodfacts/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - esnet
networks:
    esnet: